name: Build and push image

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Install Docker
        run: curl -fsSL https://get.docker.com | sh
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: install pip
        run: apt update && apt install -y python3-pip
      - uses: abatilo/actions-poetry@v2
        with:
          poetry-version: "1.6.1"
      - uses: actions/setup-node@v3
      - uses: actions/checkout@v3
      # Extract version from Poetry
      - name: Get version
        run: echo "POETRY_VERSION=$(poetry version --short)" >> $GITHUB_ENV
      - name: Build and push Docker image
        run: |
          docker build -t ajurna/cbwebreader:${{ env.POETRY_VERSION }} .
          docker push ajurna/cbwebreader:${{ env.POETRY_VERSION }}
#      - name: Build and push version
#        uses: docker/build-push-action@v4
#        with:
#          context: .
#          push: true
#          tags: ajurna/cbwebreader:latest
#      - name: Build and push latest
#        uses: docker/build-push-action@v4
#        with:
#          context: .
#          push: true
#          tags: ajurna/cbwebreader:${{poetry version -s}}
