# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-31 10:40
from __future__ import unicode_literals

from django.db import migrations

import uuid


def gen_uuid(apps, schema_editor):
    comicbook = apps.get_model("comic", "comicbook")
    for row in comicbook.objects.all():
        row.selector = uuid.uuid4()
        row.save()
    directory = apps.get_model("comic", "directory")
    for row in directory.objects.all():
        row.selector = uuid.uuid4()
        row.save()


class Migration(migrations.Migration):

    dependencies = [("comic", "0008_auto_20160331_1140")]

    operations = [migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop)]
