# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-31 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("comic", "0010_auto_20160331_1140")]

    operations = [migrations.AlterField(model_name="comicbook", name="version", field=models.IntegerField(default=1))]
