# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-04 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("comic", "0012_auto_20160401_0949")]

    operations = [
        migrations.AddField(model_name="comicstatus", name="finished", field=models.BooleanField(default=False))
    ]
