# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-05 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comic', '0014_auto_20160404_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comicbook',
            name='file_name',
            field=models.CharField(max_length=100),
        ),
    ]
