# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-13 15:31
from __future__ import unicode_literals

from django.db import migrations


def gen_feeds(apps, schema_editor):
    user_misc = apps.get_model("comic", "UserMisc")
    User = apps.get_model("auth", "user")
    for user in User.objects.all():
        user_misc.objects.create(user=user)


class Migration(migrations.Migration):
    dependencies = [("comic", "0017_usermisc")]

    operations = [migrations.RunPython(gen_feeds, reverse_code=migrations.RunPython.noop)]
