# Generated by Django 2.2.3 on 2019-07-30 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comic', '0018_auto_20170113_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comicbook',
            name='file_name',
            field=models.TextField(),
        ),
    ]
