# Generated by Django 3.2 on 2021-04-08 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comic', '0019_auto_20190730_1846'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='directory',
            options={'ordering': ['name']},
        ),
    ]
