# Generated by Django 3.2 on 2021-04-21 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comic', '0020_alter_directory_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Setting',
        ),
    ]
