# Generated by Django 3.2 on 2021-04-21 11:13

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('comic', '0021_delete_setting'),
    ]

    operations = [
        migrations.AddField(
            model_name='comicbook',
            name='thumbnail',
            field=imagekit.models.fields.ProcessedImageField(null=True, upload_to='thumbs'),
        ),
    ]
