# Generated by Django 3.2 on 2021-04-22 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comic', '0023_directory_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='comicbook',
            name='thumbnail_index',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='directory',
            name='thumbnail_index',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='directory',
            name='thumbnail_issue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='directory_thumbnail_issue', to='comic.comicbook'),
        ),
    ]
