# Generated by Django 3.2 on 2021-05-06 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comic', '0024_auto_20210422_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='directory',
            name='classification',
            field=models.PositiveSmallIntegerField(choices=[(0, 'G'), (1, 'PG'), (2, '12'), (3, '15'), (4, '18')], default=4),
        ),
        migrations.AddField(
            model_name='usermisc',
            name='allowed_to_read',
            field=models.PositiveSmallIntegerField(choices=[(0, 'G'), (1, 'PG'), (2, '12'), (3, '15'), (4, '18')], default=4),
        ),
    ]
