# Generated by Django 3.2 on 2021-05-06 12:50

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import django_boost.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comic', '0025_auto_20210506_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermisc',
            name='user',
            field=django_boost.models.fields.AutoOneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
