# Generated by Django 3.2 on 2021-05-06 12:56

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import django_boost.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comic', '0026_alter_usermisc_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermisc',
            name='id',
        ),
        migrations.AlterField(
            model_name='usermisc',
            name='user',
            field=django_boost.models.fields.AutoOneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
