# Generated by Django 3.2.3 on 2021-05-25 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comic', '0027_auto_20210506_1356'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comicpage',
            options={'ordering': ['index']},
        ),
    ]
