# Generated by Django 3.2.14 on 2022-07-07 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comic', '0028_alter_comicpage_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='comicbook',
            name='directory2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='directory2', to='comic.directory', to_field='selector'),
        ),
    ]
