# Generated by Django 3.2.14 on 2022-07-07 16:20

from django.db import migrations


def forwards_func(apps, schema_editor):
    ComicBook = apps.get_model("comic", "ComicBook")
    for comic in ComicBook.objects.all():
        if comic.directory:
            comic.directory2 = comic.directory
            comic.save()


class Migration(migrations.Migration):

    dependencies = [
        ('comic', '0029_comicbook_directory2'),
    ]

    operations = [
        migrations.RunPython(forwards_func),
    ]
