# Generated by Django 3.2.14 on 2022-07-07 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comic', '0031_remove_comicbook_directory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comicbook',
            old_name='directory2',
            new_name='directory',
        ),
    ]
