# Generated by Django 3.2.14 on 2022-07-07 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comic', '0032_rename_directory2_comicbook_directory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comicbook',
            name='directory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comic.directory', to_field='selector'),
        ),
    ]
