# Generated by Django 3.2.14 on 2022-07-08 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comic', '0033_alter_comicbook_directory'),
    ]

    operations = [
        migrations.AddField(
            model_name='directory',
            name='parent2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_new', to='comic.directory', to_field='selector'),
        ),
    ]
