# Generated by Django 3.2.14 on 2022-07-08 08:10

from django.db import migrations

def forwards_func(apps, schema_editor):
    Directory = apps.get_model("comic", "Directory")
    for directory in Directory.objects.all():
        if directory.parent:
            directory.parent2 = directory.parent
            directory.save()

def backwards_func(apps, schema_editor):
    return
    Directory = apps.get_model("comic", "Directory")
    for directory in Directory.objects.all():
        if directory.parent:
            directory.parent2 = directory.parent
            directory.save()

class Migration(migrations.Migration):

    dependencies = [
        ('comic', '0034_directory_parent2'),
    ]

    operations = [
        migrations.RunPython(forwards_func, backwards_func),
    ]
