# Generated by Django 3.2.14 on 2022-07-08 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comic', '0035_auto_20220708_0910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directory',
            name='parent',
        ),
    ]
