# Generated by Django 3.2.14 on 2022-07-08 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comic', '0036_remove_directory_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='directory',
            old_name='parent2',
            new_name='parent',
        ),
    ]
