# Generated by Django 3.2.14 on 2022-07-21 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comic', '0038_alter_directory_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='comicstatus',
            name='comic2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comic2', to='comic.comicbook', to_field='selector'),
        ),
    ]
