# Generated by Django 3.2.14 on 2022-07-21 10:21

from django.db import migrations


def forwards_func(apps, schema_editor):
    ComicStatus = apps.get_model("comic", "ComicStatus")
    for status in ComicStatus.objects.all():
        status.comic2 = status.comic
        status.save()


def backwards_func(apps, schema_editor):
    ComicStatus = apps.get_model("comic", "ComicStatus")
    for status in ComicStatus.objects.all():
        status.comic = status.comic2
        status.save()


class Migration(migrations.Migration):

    dependencies = [
        ('comic', '0039_comicstatus_comic2'),
    ]

    operations = [
        migrations.RunPython(forwards_func, backwards_func),
    ]
