# Generated by Django 3.2.14 on 2022-07-21 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comic', '0041_alter_comicstatus_comic2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comicstatus',
            name='comic',
        ),
    ]
