# Generated by Django 3.2.14 on 2022-07-21 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comic', '0042_remove_comicstatus_comic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comicstatus',
            old_name='comic2',
            new_name='comic',
        ),
    ]
