# Generated by Django 3.2.14 on 2022-07-21 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comic', '0043_rename_comic2_comicstatus_comic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comicstatus',
            name='comic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comic.comicbook', to_field='selector'),
        ),
    ]
