# Generated by Django 3.2.14 on 2022-07-22 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comic', '0044_alter_comicstatus_comic'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='comicstatus',
            constraint=models.UniqueConstraint(fields=('user', 'comic'), name='one_per_user_per_comic'),
        ),
    ]
