# Generated by Django 4.0.6 on 2022-07-22 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comic', '0045_comicstatus_one_per_user_per_comic'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='comicbook',
            constraint=models.UniqueConstraint(fields=('directory', 'file_name'), name='one_comic_name_per_directory'),
        ),
    ]
