# Generated by Django 4.0.7 on 2022-09-15 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comic', '0047_comicstatus_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='comicbook',
            name='page_count',
            field=models.IntegerField(default=0),
        ),
    ]
